
set(CTEST_PROJECT_NAME "cmake-examples")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "172.19.0.3")
set(CTEST_DROP_LOCATION "/submit.php?project=cmake-examples")
set(CTEST_DROP_SITE_CDASH TRUE)