
set(CTEST_PROJECT_NAME "tutorial")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "localhost:8080")
set(CTEST_DROP_LOCATION "/submit.php?project=tutorial")
set(CTEST_DROP_SITE_CDASH TRUE)